### ISSUE TITLE
[Reporting Dead Steps] Usage of steps having '|' operator to pass parameters are not parsed properly

### ISSUE THREAD

**Issue by christopher-rex** [r-cochran/cuke_sniffer#71] opened 2014-07-16 12:18 UTC
Say there is step which can only take certain list of values for a parameter,

>Then /^I click on (Login|Logout) button$/ do |button_name|
>  page.send(button_name.downcase).click
>end

Currently the dead steps parsing, does not consider the usage of these steps in feature files and show these steps as unused always.

**Comment by vaughncm** [comment] 2015-06-07 23:05
Analysis provided on most current gem version shows this to be working as intended. Closing. If you'd like to re-open with more info please feel free!

**Closed by vaughncm** 2015-06-07 23:05 UTC
Labels: bug
